### ISSUE TITLE
Version 0.11.1 crashes with error in NetBox v3.5.x

### ISSUE THREAD

**Issue by drygdryg** [netbox-community/netbox-bgp#168]
**NetBox version**
NetBox v3.5.9

**Describe the bug**
netbox-bgp v0.11.1  does not work in NetBox v3.5.x

**To Reproduce**
1. Install the latest version of netbox-bgp using pip.
2. Run migrations:
```
python manage.py migrate
```
3. See error `ImportError: cannot import name 'IPNetworkField' from 'ipam.api.field_serializers' `:
```
(venv) root:/opt/netbox/netbox $ python manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 97, in handle
    self.check(databases=[database])
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/urls.py", line 8, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox/netbox/extras/plugins/urls.py", line 38, in <module>
    urlpatterns = import_string(f"{plugin_path}.api.urls.urlpatterns")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_bgp/api/urls.py", line 3, in <module>
    from .views import (
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_bgp/api/views.py", line 3, in <module>
    from .serializers import (
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_bgp/api/serializers.py", line 11, in <module>
    from ipam.api.field_serializers import IPNetworkField
ImportError: cannot import name 'IPNetworkField' from 'ipam.api.field_serializers' (/opt/netbox/netbox/ipam/api/field_serializers.py)
```
**Additional context**
It looks like version 0.11.0 is working correctly.

**Comment by telescope40** [comment]
Just wanted to add that I did reproduce the issue as well  with netbox-bgp  .12.1 on  Netbox v3.5-2.6.1 (latest seemed to have the same issue)

hardcoding netbox-bgp==0.11.0 resolved the error 


`redis-1                | 1:M 23 Mar 2024 11:55:05.528 * Ready to accept connections
netbox-1               | 🧬 loaded config '/etc/netbox/config/configuration.py'
netbox-1               | 🧬 loaded config '/etc/netbox/config/extra.py'
netbox-1               | 🧬 loaded config '/etc/netbox/config/logging.py'
netbox-1               | 🧬 loaded config '/etc/netbox/config/plugins.py'
netbox-1               | Traceback (most recent call last):
netbox-1               |   File "/opt/netbox/netbox/./manage.py", line 10, in <module>
netbox-1               |     execute_from_command_line(sys.argv)
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
netbox-1               |     utility.execute()
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
netbox-1               |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
netbox-1               |     self.execute(*args, **cmd_options)
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 443, in execute
netbox-1               |     self.check()
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 475, in check
netbox-1               |     all_issues = checks.run_checks(
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
netbox-1               |     new_errors = check(app_configs=app_configs, databases=databases)
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
netbox-1               |     return check_resolver(resolver)
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
netbox-1               |     return check_method()
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
netbox-1               |     for pattern in self.url_patterns:
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
netbox-1               |     res = instance.__dict__[self.name] = self.func(instance)
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
netbox-1               |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
netbox-1               |     res = instance.__dict__[self.name] = self.func(instance)
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
netbox-1               |     return import_module(self.urlconf_name)
netbox-1               |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
netbox-1               |     return _bootstrap._gcd_import(name[level:], package, level)
netbox-1               |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
netbox-1               |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
netbox-1               |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
netbox-1               |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
netbox-1               |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
netbox-1               |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
netbox-1               |   File "/opt/netbox/netbox/netbox/urls.py", line 8, in <module>
netbox-1               |     from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
netbox-1               |   File "/opt/netbox/netbox/extras/plugins/urls.py", line 38, in <module>
netbox-1               |     urlpatterns = import_string(f"{plugin_path}.api.urls.urlpatterns")
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
netbox-1               |     return cached_import(module_path, class_name)
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in cached_import
netbox-1               |     module = import_module(module_path)
netbox-1               |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
netbox-1               |     return _bootstrap._gcd_import(name[level:], package, level)
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_bgp/api/urls.py", line 3, in <module>
netbox-1               |     from .views import (
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_bgp/api/views.py", line 3, in <module>
netbox-1               |     from .serializers import (
netbox-1               |   File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_bgp/api/serializers.py", line 11, in <module>
netbox-1               |     from ipam.api.field_serializers import IPNetworkField
netbox-1               | ImportError: cannot import name 'IPNetworkField' from 'ipam.api.field_serializers' (/opt/netbox/netbox/ipam/api/field_serializers.py)
netbox-1               | ⏳ Waiting on DB... (0s / 30s)
^CGracefully stopping... (press Ctrl+C again to force)

**Comment by pl0xym0r** [comment]
IPNetworkField came with netbox version 3.6.1 : https://github.com/netbox-community/netbox/commit/bb6b4d01c1f501e379fc767fa8b6327c927648a5
You can't use plugin latest version with your netbox 3.5, compatibility matrix is on readme even if there is an issue on compatibility values, it would be plugin 0.11.1  --> netbox  > 3.6  ///   0.11.0 netbox <= 3.5
